- name: "Install packages"
  apt:
      pkg:
        - python3
        - postgresql-{{ version }}
        - postgresql-contrib-{{ version }}
      state: present

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "{{ data }}"
  register: postgres_data

- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql