- name: Add a group called superuser
  ansible.builtin.group:
    name: superuser
    state: present

- name: Add the user 'user1'
  ansible.builtin.user:
    name: "{{ user }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /bin/bash
    groups:
      - superuser

- name: Add the user 'user2'
  ansible.builtin.user:
    name: "{{ user2 }}"
    password: "{{ user2_password | password_hash('sha512') }}"
    shell: /bin/bash
    groups:
      - superuser

- name: Copy sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/01_users
    owner: root
    group: root
    mode: u=rw,g=rw

- name: SSH keys
  authorized_key:
    user: "{{ user }}"
    state: present
    key: '{{ item }}'
  with_file:
    - files/key-sf.pub

- name: SSH keys 2
  authorized_key:
    user: "{{ user2 }}"
    state: present
    key: '{{ item }}'
  with_file:
    - files/key-sf.pub

- name: Copy sshd config
  template:
    src: templates/sshd.j2
    dest: /etc/ssh/sshd_config.d/01-users.conf
    owner: root
    group: root
    mode: u=rw,g=r
  notify:
    - Restart sshd
