# install nginx+php
- name: install nginx+php
  apt:
    name:
      - nginx
      - php-fpm
    state: present
    update_cache: yes

- name: Creates directory
  file:
    path: /opt/nginx/ansible/{{ domain }}/html
    state: directory

- name: Copy config nginx
  template:
    src: nginx_conf.j2
    dest: /etc/nginx/sites-available/{{ domain }}.conf
    owner: root
    group: root
    mode: u=rw,g=rw

- name: Create symbolic link
  file:
    src: "/etc/nginx/sites-available/{{ domain }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ domain }}.conf"
    state: link

- ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/nginx/sites-enabled/default"
    - "/etc/nginx/sites-available/default"

- name: Copy config php
  template:
    src: index_php.j2
    dest: /opt/nginx/ansible/{{ domain }}/html/index.php
    owner: root
    group: root
    mode: u=rw,g=rw
  notify:
   - restart nginx

- name: restart nginx
  become: true
  systemd:
    daemon_reload: true
    name: nginx.service
    state: restarted
