- name: Add a group called superuser
  ansible.builtin.group:
    name: superuser
    state: present

- name: Add the user 'user1'
  ansible.builtin.user:
    name: "{{ user }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /bin/bash
    groups:
      - superuser

- name: Add the user 'user2'
  ansible.builtin.user:
    name: "{{ user2 }}"
    password: "{{ user2_password | password_hash('sha512') }}"
    shell: /bin/bash
    groups:
      - superuser

- name: Copy sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/01_users
    owner: root
    group: root
    mode: u=rw,g=rw