---
# defaults file for dnsmasq
dnsmasq_addresses: "0.0.0.0"
dnsmasq_port: "53"
dnsmasq_domain: "may.local"
dnsmasq_cache: "4096"

dnsmasq_nameserver:
  - "77.88.8.1"
  - "8.8.4.4"
  - "8.8.8.8"

dnsmasq_hosts:
  - hostname: test_1
    ip: "1.2.3.4"
  - hostname: test_2
    ip: "10.20.30.40"
  - hostname: test_3
    ip: "192.168.1.2"

domain: "examplespd.org"